
/*
 * This file was generated by the SOM Compiler.
 * FileName: delphi.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.19
 *     SOM Emitter emith.dll: 2.31.1.64
 */

/*
 *         File:    DelphiEmitter.idl
 *       Author:    SOMObjects Emitter Framework
 *     Contents:    Generic framework logic class for DelphiEmitter.
 *         Date:    Sun Jan 11 00:51:12 2015.
 */


#ifndef SOM_DelphiEmitter_h
#define SOM_DelphiEmitter_h


/*
 * The SOM_STRICT_IDL macro means that we can ignore stars
 * in our declarations of objects.
 */
#define SOM_STRICT_IDL 1


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef DelphiEmitter
#define DelphiEmitter SOMObject
#endif

/*
 * Include Parent Bindings
 */
#ifndef SOM_SOMTEmitC_h
#ifdef SOMLOCALINCLUDES
#include "scemit.h"
#else
#include <scemit.h>
#endif
#endif

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef SOMStringTableC
    #define SOMStringTableC SOMObject
#endif /* SOMStringTableC */
#ifndef SOMTEntryC
    #define SOMTEntryC SOMObject
#endif /* SOMTEntryC */
#ifndef SOMTEmitC
    #define SOMTEmitC SOMObject
#endif /* SOMTEmitC */
#ifndef SOMTMetaClassEntryC
    #define SOMTMetaClassEntryC SOMObject
#endif /* SOMTMetaClassEntryC */
#ifndef SOMTAttributeEntryC
    #define SOMTAttributeEntryC SOMObject
#endif /* SOMTAttributeEntryC */
#ifndef SOMTTypedefEntryC
    #define SOMTTypedefEntryC SOMObject
#endif /* SOMTTypedefEntryC */
#ifndef SOMTBaseClassEntryC
    #define SOMTBaseClassEntryC SOMObject
#endif /* SOMTBaseClassEntryC */
#ifndef SOMTPassthruEntryC
    #define SOMTPassthruEntryC SOMObject
#endif /* SOMTPassthruEntryC */
#ifndef SOMTDataEntryC
    #define SOMTDataEntryC SOMObject
#endif /* SOMTDataEntryC */
#ifndef SOMTMethodEntryC
    #define SOMTMethodEntryC SOMObject
#endif /* SOMTMethodEntryC */
#ifndef SOMTClassEntryC
    #define SOMTClassEntryC SOMObject
#endif /* SOMTClassEntryC */
#ifndef SOMTModuleEntryC
    #define SOMTModuleEntryC SOMObject
#endif /* SOMTModuleEntryC */
#ifndef SOMTParameterEntryC
    #define SOMTParameterEntryC SOMObject
#endif /* SOMTParameterEntryC */
#ifndef SOMTStructEntryC
    #define SOMTStructEntryC SOMObject
#endif /* SOMTStructEntryC */
#ifndef SOMTUnionEntryC
    #define SOMTUnionEntryC SOMObject
#endif /* SOMTUnionEntryC */
#ifndef SOMTEnumEntryC
    #define SOMTEnumEntryC SOMObject
#endif /* SOMTEnumEntryC */
#ifndef SOMTConstEntryC
    #define SOMTConstEntryC SOMObject
#endif /* SOMTConstEntryC */
#ifndef SOMTSequenceEntryC
    #define SOMTSequenceEntryC SOMObject
#endif /* SOMTSequenceEntryC */
#ifndef SOMTStringEntryC
    #define SOMTStringEntryC SOMObject
#endif /* SOMTStringEntryC */
#ifndef SOMTEnumNameEntryC
    #define SOMTEnumNameEntryC SOMObject
#endif /* SOMTEnumNameEntryC */
#ifndef SOMTCommonEntryC
    #define SOMTCommonEntryC SOMObject
#endif /* SOMTCommonEntryC */
#ifndef SOMTUserDefinedTypeEntryC
    #define SOMTUserDefinedTypeEntryC SOMObject
#endif /* SOMTUserDefinedTypeEntryC */

/*
 * End of bindings for IDL types.
 */

#define DelphiEmitter_MajorVersion 1
#define DelphiEmitter_MinorVersion 1

/*
 * Declare the class creation procedure
 */
SOMEXTERN 
#if defined(SOM_Module_delphi_Source)
        SOMDLLEXPORT
#else
    SOMDLLIMPORT
#endif
 SOMClass  SOMLINK DelphiEmitterNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);

/*
 * Declare the ABI 2 ClassData structure
 */
SOMEXTERN struct DelphiEmitterClassDataStructure {
	SOMClass classObject;
} 
#if defined(SOM_Module_delphi_Source)
        SOMDLLEXPORT
#else
    SOMDLLIMPORT
#endif
 SOMDLINK DelphiEmitterClassData;

/*
 * Declare the ABI 2 CClassData structure
 */
SOMEXTERN struct DelphiEmitterCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} 
#if defined(SOM_Module_delphi_Source)
        SOMDLLEXPORT
#else
    SOMDLLIMPORT
#endif
 SOMDLINK DelphiEmitterCClassData;

/*
 * Class Object and Method Token Macros
 */
#define _SOMCLASS_DelphiEmitter (DelphiEmitterClassData.classObject)
#ifndef SOMGD_DelphiEmitter
    #if (defined(_DelphiEmitter) || defined(__DelphiEmitter))
        #undef _DelphiEmitter
        #undef __DelphiEmitter
        #define SOMGD_DelphiEmitter 1
    #else
        #define _DelphiEmitter _SOMCLASS_DelphiEmitter
    #endif /* _DelphiEmitter */
#endif /* SOMGD_DelphiEmitter */
#define DelphiEmitter_classObj _SOMCLASS_DelphiEmitter
#define _SOMMTOKEN_DelphiEmitter(method) ((somMToken)DelphiEmitterClassData.method)

/*
 * New and Renew macros for DelphiEmitter
 */
#define DelphiEmitterNew() \
   ( _DelphiEmitter ? \
	_somNew(_DelphiEmitter) \
	: ( DelphiEmitterNewClass(\
		DelphiEmitter_MajorVersion, \
		DelphiEmitter_MinorVersion),\
	   _somNew(_DelphiEmitter)))
#define DelphiEmitterRenew(buf) \
   ( _DelphiEmitter ? \
	_somRenew(_DelphiEmitter, buf) \
	: ( DelphiEmitterNewClass(\
		DelphiEmitter_MajorVersion, \
		DelphiEmitter_MinorVersion),\
	   _somRenew(_DelphiEmitter, buf)))

/*
 * Full Names for Inherited Methods
 */
/* overridden methods */
#define DelphiEmitter_somtGenerateSections SOMTEmitC_somtGenerateSections

#ifndef SOM_DONT_USE_INHERITED_MACROS
#define DelphiEmitter__get_somtTemplate SOMTEmitC__get_somtTemplate
#define DelphiEmitter__set_somtTemplate SOMTEmitC__set_somtTemplate
#define DelphiEmitter__get_somtTargetFile SOMTEmitC__get_somtTargetFile
#define DelphiEmitter__set_somtTargetFile SOMTEmitC__set_somtTargetFile
#define DelphiEmitter__get_somtTargetClass SOMTEmitC__get_somtTargetClass
#define DelphiEmitter__set_somtTargetClass SOMTEmitC__set_somtTargetClass
#define DelphiEmitter__get_somtTargetModule SOMTEmitC__get_somtTargetModule
#define DelphiEmitter__set_somtTargetModule SOMTEmitC__set_somtTargetModule
#define DelphiEmitter__get_somtTargetType SOMTEmitC__get_somtTargetType
#define DelphiEmitter__set_somtTargetType SOMTEmitC__set_somtTargetType
#define DelphiEmitter__get_somtEmitterName SOMTEmitC__get_somtEmitterName
#define DelphiEmitter__set_somtEmitterName SOMTEmitC__set_somtEmitterName
#define DelphiEmitter_somtOpenSymbolsFile SOMTEmitC_somtOpenSymbolsFile
#define DelphiEmitter_somtSetPredefinedSymbols SOMTEmitC_somtSetPredefinedSymbols
#define DelphiEmitter_somtFileSymbols SOMTEmitC_somtFileSymbols
#define DelphiEmitter_somtEmitProlog SOMTEmitC_somtEmitProlog
#define DelphiEmitter_somtEmitBaseIncludesProlog SOMTEmitC_somtEmitBaseIncludesProlog
#define DelphiEmitter_somtEmitBaseIncludes SOMTEmitC_somtEmitBaseIncludes
#define DelphiEmitter_somtEmitBaseIncludesEpilog SOMTEmitC_somtEmitBaseIncludesEpilog
#define DelphiEmitter_somtEmitMetaInclude SOMTEmitC_somtEmitMetaInclude
#define DelphiEmitter_somtEmitClass SOMTEmitC_somtEmitClass
#define DelphiEmitter_somtEmitMeta SOMTEmitC_somtEmitMeta
#define DelphiEmitter_somtEmitBaseProlog SOMTEmitC_somtEmitBaseProlog
#define DelphiEmitter_somtEmitBase SOMTEmitC_somtEmitBase
#define DelphiEmitter_somtEmitBaseEpilog SOMTEmitC_somtEmitBaseEpilog
#define DelphiEmitter_somtEmitPassthruProlog SOMTEmitC_somtEmitPassthruProlog
#define DelphiEmitter_somtEmitPassthru SOMTEmitC_somtEmitPassthru
#define DelphiEmitter_somtEmitPassthruEpilog SOMTEmitC_somtEmitPassthruEpilog
#define DelphiEmitter_somtEmitRelease SOMTEmitC_somtEmitRelease
#define DelphiEmitter_somtEmitDataProlog SOMTEmitC_somtEmitDataProlog
#define DelphiEmitter_somtEmitData SOMTEmitC_somtEmitData
#define DelphiEmitter_somtEmitDataEpilog SOMTEmitC_somtEmitDataEpilog
#define DelphiEmitter_somtEmitAttributeProlog SOMTEmitC_somtEmitAttributeProlog
#define DelphiEmitter_somtEmitAttribute SOMTEmitC_somtEmitAttribute
#define DelphiEmitter_somtEmitAttributeEpilog SOMTEmitC_somtEmitAttributeEpilog
#define DelphiEmitter_somtEmitConstantProlog SOMTEmitC_somtEmitConstantProlog
#define DelphiEmitter_somtEmitConstant SOMTEmitC_somtEmitConstant
#define DelphiEmitter_somtEmitConstantEpilog SOMTEmitC_somtEmitConstantEpilog
#define DelphiEmitter_somtEmitTypedefProlog SOMTEmitC_somtEmitTypedefProlog
#define DelphiEmitter_somtEmitTypedef SOMTEmitC_somtEmitTypedef
#define DelphiEmitter_somtEmitTypedefEpilog SOMTEmitC_somtEmitTypedefEpilog
#define DelphiEmitter_somtEmitStructProlog SOMTEmitC_somtEmitStructProlog
#define DelphiEmitter_somtEmitStruct SOMTEmitC_somtEmitStruct
#define DelphiEmitter_somtEmitStructEpilog SOMTEmitC_somtEmitStructEpilog
#define DelphiEmitter_somtEmitUnionProlog SOMTEmitC_somtEmitUnionProlog
#define DelphiEmitter_somtEmitUnion SOMTEmitC_somtEmitUnion
#define DelphiEmitter_somtEmitUnionEpilog SOMTEmitC_somtEmitUnionEpilog
#define DelphiEmitter_somtEmitEnumProlog SOMTEmitC_somtEmitEnumProlog
#define DelphiEmitter_somtEmitEnum SOMTEmitC_somtEmitEnum
#define DelphiEmitter_somtEmitEnumEpilog SOMTEmitC_somtEmitEnumEpilog
#define DelphiEmitter_somtEmitInterfaceProlog SOMTEmitC_somtEmitInterfaceProlog
#define DelphiEmitter_somtEmitInterface SOMTEmitC_somtEmitInterface
#define DelphiEmitter_somtEmitInterfaceEpilog SOMTEmitC_somtEmitInterfaceEpilog
#define DelphiEmitter_somtEmitModuleProlog SOMTEmitC_somtEmitModuleProlog
#define DelphiEmitter_somtEmitModule SOMTEmitC_somtEmitModule
#define DelphiEmitter_somtEmitModuleEpilog SOMTEmitC_somtEmitModuleEpilog
#define DelphiEmitter_somtEmitMethodsProlog SOMTEmitC_somtEmitMethodsProlog
#define DelphiEmitter_somtEmitMethods SOMTEmitC_somtEmitMethods
#define DelphiEmitter_somtEmitMethodsEpilog SOMTEmitC_somtEmitMethodsEpilog
#define DelphiEmitter_somtEmitMethod SOMTEmitC_somtEmitMethod
#define DelphiEmitter_somtEmitEpilog SOMTEmitC_somtEmitEpilog
#define DelphiEmitter_somtScanBases SOMTEmitC_somtScanBases
#define DelphiEmitter_somtCheckVisibility SOMTEmitC_somtCheckVisibility
#define DelphiEmitter_somtNew SOMTEmitC_somtNew
#define DelphiEmitter_somtImplemented SOMTEmitC_somtImplemented
#define DelphiEmitter_somtOverridden SOMTEmitC_somtOverridden
#define DelphiEmitter_somtInherited SOMTEmitC_somtInherited
#define DelphiEmitter_somtAllVisible SOMTEmitC_somtAllVisible
#define DelphiEmitter_somtAll SOMTEmitC_somtAll
#define DelphiEmitter_somtNewNoProc SOMTEmitC_somtNewNoProc
#define DelphiEmitter_somtPrivOrPub SOMTEmitC_somtPrivOrPub
#define DelphiEmitter_somtNewProc SOMTEmitC_somtNewProc
#define DelphiEmitter_somtLink SOMTEmitC_somtLink
#define DelphiEmitter_somtVA SOMTEmitC_somtVA
#define DelphiEmitter_somtScanMethods SOMTEmitC_somtScanMethods
#define DelphiEmitter_somtScanConstants SOMTEmitC_somtScanConstants
#define DelphiEmitter_somtScanTypedefs SOMTEmitC_somtScanTypedefs
#define DelphiEmitter_somtScanStructs SOMTEmitC_somtScanStructs
#define DelphiEmitter_somtScanUnions SOMTEmitC_somtScanUnions
#define DelphiEmitter_somtScanEnums SOMTEmitC_somtScanEnums
#define DelphiEmitter_somtScanData SOMTEmitC_somtScanData
#define DelphiEmitter_somtScanAttributes SOMTEmitC_somtScanAttributes
#define DelphiEmitter_somtScanInterfaces SOMTEmitC_somtScanInterfaces
#define DelphiEmitter_somtScanModules SOMTEmitC_somtScanModules
#define DelphiEmitter_somtScanPassthru SOMTEmitC_somtScanPassthru
#define DelphiEmitter_somtEmitFullPassthru SOMTEmitC_somtEmitFullPassthru
#define DelphiEmitter_somtScanDataF SOMTEmitC_somtScanDataF
#define DelphiEmitter_somtScanBasesF SOMTEmitC_somtScanBasesF
#define DelphiEmitter_somtGetGlobalModifierValue SOMTEmitC_somtGetGlobalModifierValue
#define DelphiEmitter_somtGetFirstGlobalDefinition SOMTEmitC_somtGetFirstGlobalDefinition
#define DelphiEmitter_somtGetNextGlobalDefinition SOMTEmitC_somtGetNextGlobalDefinition
#define DelphiEmitter_somInit SOMObject_somInit
#define DelphiEmitter_somUninit SOMObject_somUninit
#define DelphiEmitter_somDumpSelfInt SOMObject_somDumpSelfInt
#define DelphiEmitter_somDefaultInit SOMObject_somDefaultInit
#define DelphiEmitter_somDestruct SOMObject_somDestruct
#define DelphiEmitter_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define DelphiEmitter_somDefaultAssign SOMObject_somDefaultAssign
#define DelphiEmitter_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define DelphiEmitter_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define DelphiEmitter_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define DelphiEmitter_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define DelphiEmitter_somDefaultVAssign SOMObject_somDefaultVAssign
#define DelphiEmitter_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define DelphiEmitter_somFree SOMObject_somFree
#define DelphiEmitter_somGetClass SOMObject_somGetClass
#define DelphiEmitter_somGetClassName SOMObject_somGetClassName
#define DelphiEmitter_somGetSize SOMObject_somGetSize
#define DelphiEmitter_somIsA SOMObject_somIsA
#define DelphiEmitter_somIsInstanceOf SOMObject_somIsInstanceOf
#define DelphiEmitter_somRespondsTo SOMObject_somRespondsTo
#define DelphiEmitter_somDispatch SOMObject_somDispatch
#define DelphiEmitter_somClassDispatch SOMObject_somClassDispatch
#define DelphiEmitter_somCastObj SOMObject_somCastObj
#define DelphiEmitter_somResetObj SOMObject_somResetObj
#define DelphiEmitter_somPrintSelf SOMObject_somPrintSelf
#define DelphiEmitter_somDumpSelf SOMObject_somDumpSelf
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_DelphiEmitter_h */
